- name: "irods db user: {{dbuser}}"
  postgresql_user:
    name: "{{dbuser}}"
    password: "{{dbpassword}}"
  become: yes
  become_user: postgres
- name: "irods database: {{dbname}}"
  postgresql_db:
    name: "{{dbname}}"
    owner: "{{dbuser}}"
  become: yes
  become_user: postgres
- name: irods db grants
  postgresql_privs:
    db: "{{dbname}}"
    privs: ALL
    roles: "{{dbuser}}"
    type: database
  become: yes
  become_user: postgres