- name: "irods db user: {{dbuser}}"
  postgresql_user:
    name: "{{dbuser}}"
    password: "{{dbpassword}}"
  become: yes
  become_user: postgres
- name: "irods database: {{dbname}}"
  postgresql_db:
    name: "{{dbname}}"
    owner: "{{dbuser}}"
  become: yes
  become_user: postgres
- name: irods db grants
  postgresql_privs:
    db: "{{dbname}}"
    privs: ALL
    roles: "{{dbuser}}"
    type: database
  become: yes
  become_user: postgres
- name: Add source repository into sources list
  apt_repository:
    repo: deb [arch=amd64] https://packages.irods.org/apt/ {{ ansible_lsb.codename }} main
    state: present
- name: irods apt key
  apt_key:
    url: https://packages.irods.org/irods-signing-key.asc
    state: present
- name: install software
  package:
    name:
      - python3-pyodbc
      - irods-server
      - irods-database-plugin-postgres
- name: "create setup json: {{irods_json}}"
  template:
    src: irods.json.j2
    dest: "{{irods_json}}"
- name: "run irods setup"
  command: 
    cmd: "python3 /var/lib/irods/scripts/setup_irods.py --json_configuration_file {{ irods_json }}"
    creates: /var/lib/irods/.irods/irods_environment.json
- name: run irods
  service:
    name: irods
    state: started

