- name: install database
  package:
    name:
      - postgresql
      - python3-psycopg2
- name: find port
  shell: "grep ^port /etc/postgresql/*/main/* | awk -F= '{print $2}' | awk '{print $1}'"
  register: postgresgrep
- debug: msg="{{postgresgrep.stdout}}"
- set_fact:
    postgresql_port: "{{postgresgrep.stdout}}"